/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "FJFX.h"
/* Header for class com_kit_fingerprintcapture_template_TemplateExtractor */

#ifndef _Included_com_kit_fingerprintcapture_template_TemplateExtractor
#define _Included_com_kit_fingerprintcapture_template_TemplateExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kit_fingerprintcapture_template_TemplateExtractor
 * Method:    createFmdFromRaw
 * Signature: ([BIIII[B[I)I
 */
JNIEXPORT int JNICALL Java_com_kit_fingerprintcapture_template_TemplateExtractor_createFmdFromRaw
  (JNIEnv *, jobject , jbyteArray, jint, jint, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
